export const ENTRY_STATES = [
  'IDLE', 'SCANNED', 'CHECKLIST_PENDING', 'ENTERED', 'ACTIVE',
  'EXITED', 'OVERSTAY_ALERT', 'SOS_TRIGGERED', 'GAS_ALERT', 'CHECKIN_MISSED',
] as const;

export const ENTRY_EVENTS = [
  'SCAN_QR', 'COMPLETE_CHECKLIST', 'CONFIRM_ENTRY', 'ACTIVATE',
  'CONFIRM_EXIT', 'TRIGGER_ALERT', 'TRIGGER_SOS', 'GAS_DANGER',
  'MISS_CHECKIN', 'RESOLVE_CHECKIN', 'RESOLVE_GAS', 'CANCEL_SOS', 'RESET',
] as const;
