import type { EntryState } from '../types/entry-log';

type EntryEvent =
  | 'SCAN_QR' | 'COMPLETE_CHECKLIST' | 'CONFIRM_ENTRY' | 'ACTIVATE'
  | 'CONFIRM_EXIT' | 'TRIGGER_ALERT' | 'TRIGGER_SOS' | 'GAS_DANGER'
  | 'MISS_CHECKIN' | 'RESOLVE_CHECKIN' | 'RESOLVE_GAS' | 'CANCEL_SOS' | 'RESET';

export const STATE_TRANSITIONS: Record<EntryState, Partial<Record<EntryEvent, EntryState>>> = {
  IDLE: {
    SCAN_QR: 'SCANNED',
  },
  SCANNED: {
    COMPLETE_CHECKLIST: 'CHECKLIST_PENDING',
    RESET: 'IDLE',
  },
  CHECKLIST_PENDING: {
    CONFIRM_ENTRY: 'ENTERED',
    RESET: 'IDLE',
  },
  ENTERED: {
    ACTIVATE: 'ACTIVE',
    CONFIRM_EXIT: 'EXITED',
    RESET: 'IDLE',
  },
  ACTIVE: {
    CONFIRM_EXIT: 'EXITED',
    TRIGGER_ALERT: 'OVERSTAY_ALERT',
    GAS_DANGER: 'GAS_ALERT',
    MISS_CHECKIN: 'CHECKIN_MISSED',
    TRIGGER_SOS: 'SOS_TRIGGERED',
  },
  EXITED: {
    RESET: 'IDLE',
  },
  OVERSTAY_ALERT: {
    CONFIRM_EXIT: 'EXITED',
    TRIGGER_SOS: 'SOS_TRIGGERED',
  },
  SOS_TRIGGERED: {
    CANCEL_SOS: 'ACTIVE',
    CONFIRM_EXIT: 'EXITED',
  },
  GAS_ALERT: {
    CONFIRM_EXIT: 'EXITED',
    RESOLVE_GAS: 'ACTIVE',
    TRIGGER_SOS: 'SOS_TRIGGERED',
  },
  CHECKIN_MISSED: {
    RESOLVE_CHECKIN: 'ACTIVE',
    TRIGGER_SOS: 'SOS_TRIGGERED',
    CONFIRM_EXIT: 'EXITED',
  },
};
