export type MaintenanceStatus = 'SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'OVERDUE' | 'CANCELLED';
export type MaintenanceType = 'cleaning' | 'structural' | 'sensor_calibration';

export interface Maintenance {
  id: string;
  manholeId: string;
  type: MaintenanceType;
  status: MaintenanceStatus;
  scheduledAt: Date;
  completedAt?: Date;
  assignedTeam?: string;
  notes?: string;
  autoGenerated: boolean;
  createdAt: Date;
}
