import prisma from '../config/database';
import { logger } from '../utils/logger';

export class MaintenanceService {
  async create(data: {
    manholeId: string; type: string; scheduledAt: string;
    assignedTeam?: string; notes?: string;
  }) {
    return prisma.maintenance.create({
      data: {
        manholeId: data.manholeId,
        type: data.type,
        scheduledAt: new Date(data.scheduledAt),
        assignedTeam: data.assignedTeam,
        notes: data.notes,
      },
    });
  }

  async getAll(filters?: { status?: string; manholeId?: string }) {
    return prisma.maintenance.findMany({
      where: {
        ...(filters?.status && { status: filters.status as any }),
        ...(filters?.manholeId && { manholeId: filters.manholeId }),
      },
      include: { manhole: { select: { area: true, qrCodeId: true } } },
      orderBy: { scheduledAt: 'desc' },
    });
  }

  async updateStatus(id: string, status: string, notes?: string) {
    const data: any = { status, notes };
    if (status === 'COMPLETED') {
      data.completedAt = new Date();
      const maint = await prisma.maintenance.findUnique({ where: { id } });
      if (maint) {
        await prisma.manhole.update({
          where: { id: maint.manholeId },
          data: { lastCleanedAt: new Date() },
        });
      }
    }
    return prisma.maintenance.update({ where: { id }, data });
  }

  async autoSchedule() {
    const manholes = await prisma.manhole.findMany();
    const scheduled: any[] = [];

    for (const manhole of manholes) {
      const daysSinceCleaned = manhole.lastCleanedAt
        ? (Date.now() - manhole.lastCleanedAt.getTime()) / 86400000
        : 999;

      const threshold = manhole.riskLevel === 'SAFE' ? 60 : 30;

      if (daysSinceCleaned > threshold) {
        const existing = await prisma.maintenance.findFirst({
          where: { manholeId: manhole.id, status: { in: ['SCHEDULED', 'IN_PROGRESS'] } },
        });

        if (!existing) {
          const m = await prisma.maintenance.create({
            data: {
              manholeId: manhole.id,
              type: 'cleaning',
              scheduledAt: new Date(),
              autoGenerated: true,
            },
          });
          scheduled.push(m);
        }
      }
    }

    logger.info(`Auto-scheduled ${scheduled.length} maintenance tasks`);
    return scheduled;
  }

  async checkOverdue() {
    const overdue = await prisma.maintenance.updateMany({
      where: { status: 'SCHEDULED', scheduledAt: { lt: new Date() } },
      data: { status: 'OVERDUE' },
    });

    if (overdue.count > 0) {
      logger.warn(`${overdue.count} maintenance tasks now overdue`);
    }
    return overdue.count;
  }
}
